### ISSUE TITLE
Unsafe attempt to load URL 

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#1083]
```
vender.min.js?14150:3 Unsafe attempt to load URL data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' height='0'><filter id='greyscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' /></filter></svg>#greyscale from frame with URL https://*****/schedule. Domains, protocols and ports must match
```
@OmgImAlexis any idea?.

**Comment by OmgImAlexis** [comment]
I'm really not sure, I'll look into it. What page, etc. ?

**Comment by fernandog** [comment]
As above:  https://*****/schedule

**Comment by fernandog** [comment]
@OmgImAlexis its trying to load `http://www.w3.org/2000/svg` from the message

**Comment by fernandog** [comment]
@OmgImAlexis any idea?

**Comment by Potherca** [comment]
If this is in Chrome, this seems to be the issue: http://stackoverflow.com/questions/39646388/xmlns-w3-url-for-svg-spec-now-throwing-error-in-chrome

**Comment by OmgImAlexis** [comment]
That's normal and I'm almost sure I fixed this already. w3 updated all their sites like last year to support https so I just updated the url to point to the https version. @fernandog can you confirm that line was updated in a PR you merged of mine?

**Comment by fernandog** [comment]
style.css
```css
#topcontrol {
    -webkit-filter: grayscale(100%);
    filter: grayscale(100%);
    filter: rgb(128, 128, 128);
    filter: url("data:image/svg+xml;utf8,<svg version='1.1' xmlns='https://www.w3.org/2000/svg' height='0'><filter id='greyscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' /></filter></svg>#greyscale");
}

```

**Comment by OmgImAlexis** [comment]
Okay, it looks like it may be a bug with newer versions of Chrome and may be linked to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=470601) one.

**Comment by Potherca** [comment]
I managed to fix this by moving the filter with the SVG up. Chrome then selected another filter and the the grayed-out worked in Chrome again.

**Comment by fernandog** [comment]
@Potherca can you open PR or send a diff of what you do ?

**Comment by Potherca** [comment]
I would have to check if my "fix" doesn't mess with other browsers but basically it boils down to this:

```css
#topcontrol {
    -webkit-filter: grayscale(100%);
    filter: url("data:image/svg+xml;utf8,<svg version='1.1' xmlns='https://www.w3.org/2000/svg' height='0'><filter id='greyscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' /></filter></svg>#greyscale");
    filter: grayscale(100%);
    filter: rgb(128, 128, 128);
}
```
